imports:
    - { resource: config_dev.yml }

doctrine:
    dbal:
        host: '%env(SYMFONY_DB_HOST)%'
        port: '%env(SYMFONY_DB_PORT)%'
        dbname: '%env(SYMFONY_DB_NAME)%'
        user: '%env(SYMFONY_DB_USERNAME)%'
        password: '%env(SYMFONY_DB_PASSWORD)%'

framework:
    test: ~
    session:
        storage_id: session.storage.mock_file
    profiler:
        collect: false

security:
    firewalls:
        main:
            http_basic: ~

web_profiler:
    toolbar: false
    intercept_redirects: false

swiftmailer:
    disable_delivery: true
