services:
    app.repository.plant_repository:
        class: 'AppBundle\Repository\PlantRepository'
        arguments:
            - '@doctrine.orm.entity_manager'
            - 'AppBundle\Entity\Plant'

    app.repository.task_repository:
        class: 'AppBundle\Repository\TaskRepository'
        arguments:
            - '@doctrine.orm.entity_manager'
            - 'AppBundle\Entity\Task'